### ISSUE TITLE
Following README results in "Executable product not found"

### ISSUE THREAD

**Issue by factotvm** [zweigraf/FakeBundle#1]
I've used your project before without issue, but I'm on a new machine and am running into this error when I try and run it. I briefly looked into Mint's code and see the error is originating there. I'm curious if it's me or if a new version of Mint changed things or...

**Comment by factotvm** [comment]
I noticed this: 

> Breaking: Swift packages without executable products are no longer supported

— https://github.com/yonaskolb/Mint/releases/tag/0.11.0

And, looking over your Package.swift, it seems that perhaps the lack of a `.executable` entry is the issue?

**Comment by zweigraf** [comment]
Hey!

Definitely looks like it. I haven’t used this project in a while, so I did not notice this. So your options seem to be using an older version of mint or adjusting the package.swift. 

I would appreciate a PR if you end up fixing this :)

**Comment by lrossi** [comment]
Sorry for interfering, I was eager to try out the tool in my project :)

**Comment by factotvm** [comment]
No worries! I gave a talk on Swift Package Manager on Tuesday night and recommended FakeBundle, but was so tired from preparing that I took Wednesday night off. Thank you for fixing it. I think it’s a great solution (although I didn’t like the Mint dependency before—and this issue reinforces that).

**Comment by zweigraf** [comment]
Hey, thank you for recommending this project :) 

I understand some hesitation regarding Mint, but I quite enjoyed it basically as a runner for SPM projects. Install information are not there, but I do think this project should run without mint.

In addition, mint actually has a resources solution that is less hacky than this project.

**Comment by factotvm** [comment]
Thanks @zweigraf. Huh, I'll have to check out Mint's solution, though I do like yours. :) In my talk, I also put forth the solution of using Makefiles. But, if I'm using SPM, I'd like use it directly if possible (in both Xcode via `swift package generate-xcodeproj` and on the command line). Hence my suggestion FakeBundle because it worked for both. Ideally I would keep the number of dependencies/moving parts to a minimum. Less things that can go wrong. That became evident here :)

Thanks for a great project. And thanks for the quick fix @lrossi.
